using System.Collections.Generic;
using Unity.Mathematics;
using UnityEngine;
using UnityEngine.Rendering;
using Plane = Unity.Mathematics.Geometry.Plane;

namespace MeshSlicer
{
    // Naive single-threaded slicer. Slices a single-submesh mesh by an arbitrary plane,
    // returning two meshes (one per side of the plane) with caps generated by fan-
    // triangulation of the cut cross-section around its centroid. Assumes the input
    // is a closed manifold and that the cross-section is a single simple polygon
    // (convex shapes are always handled correctly).
    public static class NaiveMeshSlicer
    {
        struct Vertex
        {
            public Vector3 Pos;
            public Vector3 Nrm;
            public Vector4 Tan;
            public Vector2 Uv;
        }

        struct SideBuffers
        {
            public List<Vector3> Pos;
            public List<Vector3> Nrm;
            public List<Vector4> Tan;
            public List<Vector2> Uv;
            public List<int> Tri;

            public static SideBuffers New() => new SideBuffers
            {
                Pos = new List<Vector3>(),
                Nrm = new List<Vector3>(),
                Tan = new List<Vector4>(),
                Uv  = new List<Vector2>(),
                Tri = new List<int>(),
            };

            public int Add(in Vertex v)
            {
                int i = Pos.Count;
                Pos.Add(v.Pos); Nrm.Add(v.Nrm); Tan.Add(v.Tan); Uv.Add(v.Uv);
                return i;
            }
        }

        public static SliceResult Slice(Mesh source, Plane plane)
        {
            var srcPos = source.vertices;
            var srcNrm = source.normals;
            var srcTan = source.tangents;
            var srcUv  = source.uv;
            var srcTri = source.triangles;

            bool hasNrm = srcNrm != null && srcNrm.Length == srcPos.Length;
            bool hasTan = srcTan != null && srcTan.Length == srcPos.Length;
            bool hasUv  = srcUv  != null && srcUv.Length  == srcPos.Length;

            // Normalize plane so SignedDistanceToPoint is metric.
            plane = Plane.Normalize(plane);
            float3 nN = plane.Normal;

            var dist = new float[srcPos.Length];
            for (int i = 0; i < srcPos.Length; i++)
                dist[i] = plane.SignedDistanceToPoint(srcPos[i]);

            var pos = SideBuffers.New();
            var neg = SideBuffers.New();

            // Cached interpolated body vertex per (lo,hi) edge per side.
            var cutPosIdx = new Dictionary<long, int>();
            var cutNegIdx = new Dictionary<long, int>();
            // Unique cut intersection point per edge (used for cap construction).
            var capPoints = new List<float3>();
            var capByEdge = new Dictionary<long, int>();

            int GetOrAddBodyCut(int a, int b, in Vertex v, Dictionary<long, int> cache, SideBuffers side)
            {
                long key = a < b ? ((long)a << 32) | (uint)b : ((long)b << 32) | (uint)a;
                if (cache.TryGetValue(key, out var idx)) return idx;
                idx = side.Add(v);
                cache[key] = idx;
                return idx;
            }

            int GetOrAddCapPoint(int a, int b, float3 p)
            {
                long key = a < b ? ((long)a << 32) | (uint)b : ((long)b << 32) | (uint)a;
                if (capByEdge.TryGetValue(key, out var idx)) return idx;
                idx = capPoints.Count;
                capPoints.Add(p);
                capByEdge[key] = idx;
                return idx;
            }

            // Per-vertex side cache for original vertices (so we add each only once per side).
            var origPosIdx = new int[srcPos.Length];
            var origNegIdx = new int[srcPos.Length];
            for (int i = 0; i < srcPos.Length; i++) { origPosIdx[i] = -1; origNegIdx[i] = -1; }

            int GetOrAddOriginal(int i, SideBuffers side, int[] cache)
            {
                if (cache[i] >= 0) return cache[i];
                var v = new Vertex
                {
                    Pos = srcPos[i],
                    Nrm = hasNrm ? srcNrm[i] : Vector3.zero,
                    Tan = hasTan ? srcTan[i] : Vector4.zero,
                    Uv  = hasUv  ? srcUv[i]  : Vector2.zero,
                };
                int idx = side.Add(v);
                cache[i] = idx;
                return idx;
            }

            Vertex InterpVertex(int a, int b)
            {
                // Always interpolate from min(a,b) to max(a,b) to keep results bitwise stable across calls.
                int lo = math.min(a, b), hi = math.max(a, b);
                float da = dist[lo], db = dist[hi];
                float t = da / (da - db);
                var v = new Vertex { Pos = Vector3.LerpUnclamped(srcPos[lo], srcPos[hi], t) };
                if (hasNrm) v.Nrm = Vector3.Normalize(Vector3.LerpUnclamped(srcNrm[lo], srcNrm[hi], t));
                if (hasTan)
                {
                    var tn = Vector4.LerpUnclamped(srcTan[lo], srcTan[hi], t);
                    var t3 = new Vector3(tn.x, tn.y, tn.z).normalized;
                    v.Tan = new Vector4(t3.x, t3.y, t3.z, srcTan[lo].w);
                }
                if (hasUv) v.Uv = Vector2.LerpUnclamped(srcUv[lo], srcUv[hi], t);
                return v;
            }

            for (int t = 0; t < srcTri.Length; t += 3)
            {
                int i0 = srcTri[t], i1 = srcTri[t + 1], i2 = srcTri[t + 2];
                float d0 = dist[i0], d1 = dist[i1], d2 = dist[i2];
                int s0 = d0 >= 0 ? 1 : -1;
                int s1 = d1 >= 0 ? 1 : -1;
                int s2 = d2 >= 0 ? 1 : -1;
                int sumSign = s0 + s1 + s2;

                if (sumSign == 3)
                {
                    // All positive.
                    int a = GetOrAddOriginal(i0, pos, origPosIdx);
                    int b = GetOrAddOriginal(i1, pos, origPosIdx);
                    int c = GetOrAddOriginal(i2, pos, origPosIdx);
                    pos.Tri.Add(a); pos.Tri.Add(b); pos.Tri.Add(c);
                    continue;
                }
                if (sumSign == -3)
                {
                    int a = GetOrAddOriginal(i0, neg, origNegIdx);
                    int b = GetOrAddOriginal(i1, neg, origNegIdx);
                    int c = GetOrAddOriginal(i2, neg, origNegIdx);
                    neg.Tri.Add(a); neg.Tri.Add(b); neg.Tri.Add(c);
                    continue;
                }

                // Mixed: identify the "solo" vertex whose sign differs from the other two.
                int solo;
                int sideOfSolo;
                if (s0 != s1 && s0 != s2) { solo = 0; sideOfSolo = s0; }
                else if (s1 != s0 && s1 != s2) { solo = 1; sideOfSolo = s1; }
                else { solo = 2; sideOfSolo = s2; }

                int A = (solo + 1) % 3;
                int B = (solo + 2) % 3;
                int iSolo = srcTri[t + solo];
                int iA    = srcTri[t + A];
                int iB    = srcTri[t + B];

                // Cuts on edges (solo, A) and (B, solo).
                var vP = InterpVertex(iSolo, iA);
                var vQ = InterpVertex(iB, iSolo);
                float3 pP = vP.Pos;
                float3 pQ = vQ.Pos;

                // Cap intersection points (deduped by undirected edge).
                int capP = GetOrAddCapPoint(iSolo, iA, pP);
                int capQ = GetOrAddCapPoint(iB, iSolo, pQ);

                // Build solo-side triangle and other-side quad-as-two-triangles.
                if (sideOfSolo == 1)
                {
                    int s = GetOrAddOriginal(iSolo, pos, origPosIdx);
                    int p = GetOrAddBodyCut(iSolo, iA, vP, cutPosIdx, pos);
                    int q = GetOrAddBodyCut(iB, iSolo, vQ, cutPosIdx, pos);
                    pos.Tri.Add(s); pos.Tri.Add(p); pos.Tri.Add(q);

                    int a = GetOrAddOriginal(iA, neg, origNegIdx);
                    int b = GetOrAddOriginal(iB, neg, origNegIdx);
                    int p2 = GetOrAddBodyCut(iSolo, iA, vP, cutNegIdx, neg);
                    int q2 = GetOrAddBodyCut(iB, iSolo, vQ, cutNegIdx, neg);
                    // Quad (A, B, Q, P) → triangles (A,B,Q) and (A,Q,P).
                    neg.Tri.Add(a); neg.Tri.Add(b); neg.Tri.Add(q2);
                    neg.Tri.Add(a); neg.Tri.Add(q2); neg.Tri.Add(p2);
                }
                else
                {
                    int s = GetOrAddOriginal(iSolo, neg, origNegIdx);
                    int p = GetOrAddBodyCut(iSolo, iA, vP, cutNegIdx, neg);
                    int q = GetOrAddBodyCut(iB, iSolo, vQ, cutNegIdx, neg);
                    neg.Tri.Add(s); neg.Tri.Add(p); neg.Tri.Add(q);

                    int a = GetOrAddOriginal(iA, pos, origPosIdx);
                    int b = GetOrAddOriginal(iB, pos, origPosIdx);
                    int p2 = GetOrAddBodyCut(iSolo, iA, vP, cutPosIdx, pos);
                    int q2 = GetOrAddBodyCut(iB, iSolo, vQ, cutPosIdx, pos);
                    pos.Tri.Add(a); pos.Tri.Add(b); pos.Tri.Add(q2);
                    pos.Tri.Add(a); pos.Tri.Add(q2); pos.Tri.Add(p2);
                }
            }

            // Cap construction.
            if (capPoints.Count >= 3)
            {
                BuildCap(capPoints, plane, +1, ref pos);
                BuildCap(capPoints, plane, -1, ref neg);
            }

            return new SliceResult(BuildMesh(pos, source.name + "_Pos"),
                                   BuildMesh(neg, source.name + "_Neg"));
        }

        // Fan-triangulate cap polygon around centroid.
        // capSide = +1 for positive piece (cap normal = -plane.normal),
        // capSide = -1 for negative piece (cap normal = +plane.normal).
        static void BuildCap(List<float3> capPoints, Plane plane, int capSide, ref SideBuffers side)
        {
            var basis = new PlaneBasis(plane.Normal);
            float3 centroid = float3.zero;
            for (int i = 0; i < capPoints.Count; i++) centroid += capPoints[i];
            centroid /= capPoints.Count;

            // Sort by angle around centroid in plane-local 2D.
            var indices = new int[capPoints.Count];
            var angles  = new float[capPoints.Count];
            float2 c2 = basis.Project(centroid);
            for (int i = 0; i < capPoints.Count; i++)
            {
                indices[i] = i;
                float2 d = basis.Project(capPoints[i]) - c2;
                angles[i] = math.atan2(d.y, d.x);
            }
            System.Array.Sort(angles, indices);

            float3 capNormal = capSide == 1 ? (float3)(-plane.Normal) : (float3)plane.Normal;
            // UV: planar projection in plane-local coords. Scale to roughly fit [0,1].
            // Compute bounding box in 2D and normalize.
            float2 mn = new float2(float.PositiveInfinity);
            float2 mx = new float2(float.NegativeInfinity);
            for (int i = 0; i < capPoints.Count; i++)
            {
                var p2 = basis.Project(capPoints[i]);
                mn = math.min(mn, p2);
                mx = math.max(mx, p2);
            }
            float2 size = math.max(mx - mn, new float2(1e-6f));

            // Add centroid as cap vertex.
            int centroidIdx = side.Add(new Vertex
            {
                Pos = centroid,
                Nrm = capNormal,
                Tan = new Vector4(basis.U.x, basis.U.y, basis.U.z, 1f),
                Uv  = (Vector2)((c2 - mn) / size),
            });

            int n = capPoints.Count;
            int[] capIdx = new int[n];
            for (int i = 0; i < n; i++)
            {
                var p3 = capPoints[indices[i]];
                var p2 = basis.Project(p3);
                capIdx[i] = side.Add(new Vertex
                {
                    Pos = p3,
                    Nrm = capNormal,
                    Tan = new Vector4(basis.U.x, basis.U.y, basis.U.z, 1f),
                    Uv  = (Vector2)((p2 - mn) / size),
                });
            }

            // Triangle order depends on which side. atan2 sort yields CCW from +N view.
            // Negative cap (normal = +N) needs CCW from +N view → (centroid, p[i], p[i+1]).
            // Positive cap (normal = -N) needs CCW from -N view → reverse winding.
            for (int i = 0; i < n; i++)
            {
                int j = (i + 1) % n;
                if (capSide == -1)
                {
                    side.Tri.Add(centroidIdx);
                    side.Tri.Add(capIdx[i]);
                    side.Tri.Add(capIdx[j]);
                }
                else
                {
                    side.Tri.Add(centroidIdx);
                    side.Tri.Add(capIdx[j]);
                    side.Tri.Add(capIdx[i]);
                }
            }
        }

        static Mesh BuildMesh(SideBuffers side, string name)
        {
            if (side.Pos.Count == 0 || side.Tri.Count == 0) return null;
            var m = new Mesh { name = name, indexFormat = IndexFormat.UInt32 };
            m.SetVertices(side.Pos);
            if (side.Nrm.Count == side.Pos.Count) m.SetNormals(side.Nrm);
            if (side.Tan.Count == side.Pos.Count) m.SetTangents(side.Tan);
            if (side.Uv.Count == side.Pos.Count)  m.SetUVs(0, side.Uv);
            m.SetTriangles(side.Tri, 0, true);
            m.RecalculateBounds();
            return m;
        }
    }
}
